name: Setup Cerbero
description: >-
  Creates a Cerbero configuration file and sets the ANDROID_ARCH
  and ANDROID_CONFIG environment variables.

inputs:
  target_arch:
    description: 'Target Architecture'
    required: true
    type: string

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        ANDROID_ARCH=${{ inputs.target_arch }}
        ANDROID_ARCH=${ANDROID_ARCH//_/-}
        tee -a $GITHUB_ENV <<< "ANDROID_ARCH=$ANDROID_ARCH"
        tee -a $GITHUB_ENV <<< "ANDROID_CONFIG=config/cross-android-$ANDROID_ARCH.cbc"
        tee local.cbc <<EOF
        use_ccache = True
        local_sources = "$HOME/cerbero-sources"
        home_dir = "$HOME/cerbero-build-$ANDROID_ARCH"
        EOF
